In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# 📌 Totaux connus par organisme
totaux_transcrits = {
    "Prymnesium": 53242,
    "Dinophysis": 80589,
    "Karlodinium": 122682,
    "Lingulodinium": 94373
}

# 📁 Fichiers CSV à charger
fichiers = {
    "Lingulodinium": "/home/lauryn/Documents/Orson_results/Lingulodinium_annotations.csv",
    "Prymnesium": "/home/lauryn/Documents/Orson_results/Prymnesium_annotations.csv",
    "Dinophysis": "/home/lauryn/Documents/Orson_results/Dinophysis_annotations.csv",
    "Karlodinium": "/home/lauryn/Documents/Orson_results/Karlodinium_annotations.csv"
}

In [3]:
# 🔄 Chargement et fusion
dfs = []

for organisme, chemin in fichiers.items():
    df = pd.read_csv(chemin, comment='#', sep="\t", header=None)
    df["Organisme"] = organisme
    dfs.append(df)

# Fusionner tous les DataFrames de la liste en un seul grand DataFrame
dfs = pd.concat(dfs, ignore_index=True)

dfs.columns = [
    "Sequence_ID",
    "Seed_Ortholog",
    "E_value",
    "Score",
    "eggNOG_OGs",
    "Max_Annotation_Level",
    "COG_Category",
    "Function_Description",
    "Annotated_Gene_Name",
    "GO_Terms",
    "EC_Number",
    "KEGG_KO",
    "KEGG_Pathway",
    "KEGG_Module",
    "KEGG_Reaction",
    "KEGG_rClass",
    "KEGG_BRITE",
    "KEGG_TC",
    "CAZy",
    "BiGG_Reaction",
    "Pfam_Domains",
    "Organisme"
]

In [4]:
dfs = dfs.replace('-', pd.NA)
dfs

,Sequence_ID,Seed_Ortholog,E_value,Score,eggNOG_OGs,Max_Annotation_Level,COG_Category,Function_Description,Annotated_Gene_Name,GO_Terms,...,KEGG_Pathway,KEGG_Module,KEGG_Reaction,KEGG_rClass,KEGG_BRITE,KEGG_TC,CAZy,BiGG_Reaction,Pfam_Domains,Organisme
0,NODE_1_length_15763_cov_36.459273_g0_i0,2880.D7FN30,2.750000e-14,90.1,"COG5245@1|root,KOG3595@2759|Eukaryota",2759|Eukaryota,Z,dynein light chain binding,<NA>,<NA>,...,"ko05016,map05016",<NA>,<NA>,<NA>,"ko00000,ko00001,ko04812",<NA>,<NA>,<NA>,"AAA_5,AAA_6,AAA_7,AAA_8,AAA_9,DHC_N2,Dynein_he...",Lingulodinium
1,NODE_2_length_13913_cov_31.548410_g1_i0,99598.Cal7507_1772,2.150000e-33,152.0,"COG2931@1|root,COG3210@1|root,COG2931@2|Bacter...",1117|Cyanobacteria,Q,Haemolysin-type calcium-binding repeat (2 copies),<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"HemolysinCabind,VCBS",Lingulodinium
2,NODE_3_length_13771_cov_81.442181_g2_i0,99598.Cal7507_1772,2.190000e-42,182.0,"COG2931@1|root,COG3210@1|root,COG2931@2|Bacter...",1117|Cyanobacteria,Q,Haemolysin-type calcium-binding repeat (2 copies),<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"HemolysinCabind,VCBS",Lingulodinium
3,NODE_4_length_13567_cov_10.538758_g3_i0,34506.g5327,1.740000e-240,780.0,"COG0097@1|root,COG0098@1|root,COG0099@1|root,C...",33208|Metazoa,J,Ribosomal protein S11,MRPS11,"GO:0000028,GO:0000313,GO:0000314,GO:0000462,GO...",...,"ko03010,map03010","M00178,M00179",<NA>,<NA>,"br01610,ko00000,ko00001,ko00002,ko03011",<NA>,<NA>,<NA>,Ribosomal_S11,Lingulodinium
4,NODE_5_length_13132_cov_25.985297_g4_i0,529818.AMSG_02133T0,0.000000e+00,1387.0,"COG5126@1|root,KOG0027@2759|Eukaryota",2759|Eukaryota,DTZ,Calcium-binding protein,EFCAB2,"GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO...",...,"ko03015,ko04014,ko04015,ko04016,ko04020,ko0402...",<NA>,<NA>,<NA>,"ko00000,ko00001,ko01009,ko03019,ko03021,ko0303...",<NA>,<NA>,<NA>,"EF-hand_7,EFhand_Ca_insen",Lingulodinium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147935,rb_31299,411467.BACCAP_03832,3.600000e-25,100.0,"2DN97@1|root,32W7A@2|Bacteria,1VANB@1239|Firmi...",186801|Clostridia,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Karlodinium
147936,rb_31336,1121024.AUCD01000033_gene1958,2.080000e-12,65.9,"2DTS4@1|root,33MFD@2|Bacteria,1VKHK@1239|Firmi...",91061|Bacilli,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Karlodinium
147937,rb_31337,1499502.EV12_2437,6.340000e-04,45.4,"COG3258@1|root,COG3258@2|Bacteria,1G07V@1117|C...",1117|Cyanobacteria,C,"Component of the cytochrome b6-f complex, whic...",petA,"GO:0005575,GO:0005622,GO:0005623,GO:0009512,GO...",...,"ko00195,ko01100,map00195,map01100",M00162,<NA>,<NA>,"ko00000,ko00001,ko00002,ko00194",<NA>,<NA>,<NA>,"Apocytochr_F_C,Apocytochr_F_N",Karlodinium
147938,rb_31360,2754.EH55_12370,3.420000e-15,79.3,"COG0051@1|root,COG0051@2|Bacteria,3TB4W@508458...",508458|Synergistetes,J,Involved in the binding of tRNA to the ribosomes,rpsJ,<NA>,...,"ko03010,map03010","M00178,M00179",<NA>,<NA>,"br01610,ko00000,ko00001,ko00002,ko03011",<NA>,<NA>,<NA>,Ribosomal_S10,Karlodinium
147939,rb_31364,4792.ETI45264,9.520000e-64,204.0,"COG5201@1|root,KOG1724@2759|Eukaryota,3QASU@47...",4776|Peronosporales,O,Found in Skp1 protein family,<NA>,<NA>,...,"ko04110,ko04111,ko04114,ko04120,ko04141,ko0431...","M00379,M00380,M00381,M00382,M00387,M00407,M00411",<NA>,<NA>,"ko00000,ko00001,ko00002,ko03036,ko04121",<NA>,<NA>,<NA>,"Skp1,Skp1_POZ",Karlodinium

In [5]:
# Dictionnaire de correspondance code -> fonction
cog_functions = {
    'J': 'Translation, ribosomal structure and biogenesis',
    'A': 'RNA processing and modification',
    'K': 'Transcription',
    'L': 'Replication, recombination and repair',
    'B': 'Chromatin structure and dynamics',
    'D': 'Cell cycle control, cell division, chromosome partitioning',
    'Y': 'Nuclear structure',
    'V': 'Defense mechanisms',
    'T': 'Signal transduction mechanisms',
    'M': 'Cell wall/membrane/envelope biogenesis',
    'N': 'Cell motility',
    'Z': 'Cytoskeleton',
    'W': 'Extracellular structures',
    'U': 'Intracellular trafficking, secretion, and vesicular transport',
    'O': 'Posttranslational modification, protein turnover, chaperones',
    'C': 'Energy production and conversion',
    'G': 'Carbohydrate transport and metabolism',
    'E': 'Amino acid transport and metabolism',
    'F': 'Nucleotide transport and metabolism',
    'H': 'Coenzyme transport and metabolism',
    'I': 'Lipid transport and metabolism',
    'P': 'Inorganic ion transport and metabolism',
    'Q': 'Secondary metabolites biosynthesis, transport and catabolism',
    'R': 'General function prediction only',
    'S': 'Function unknown'
}

# Dictionnaire de correspondance code -> grande catégorie
cog_categories = {
    'J': 'INFORMATION STORAGE AND PROCESSING',
    'A': 'INFORMATION STORAGE AND PROCESSING',
    'K': 'INFORMATION STORAGE AND PROCESSING',
    'L': 'INFORMATION STORAGE AND PROCESSING',
    'B': 'INFORMATION STORAGE AND PROCESSING',
    'D': 'CELLULAR PROCESSES AND SIGNALING',
    'Y': 'CELLULAR PROCESSES AND SIGNALING',
    'V': 'CELLULAR PROCESSES AND SIGNALING',
    'T': 'CELLULAR PROCESSES AND SIGNALING',
    'M': 'CELLULAR PROCESSES AND SIGNALING',
    'N': 'CELLULAR PROCESSES AND SIGNALING',
    'Z': 'CELLULAR PROCESSES AND SIGNALING',
    'W': 'CELLULAR PROCESSES AND SIGNALING',
    'U': 'CELLULAR PROCESSES AND SIGNALING',
    'O': 'CELLULAR PROCESSES AND SIGNALING',
    'C': 'METABOLISM',
    'G': 'METABOLISM',
    'E': 'METABOLISM',
    'F': 'METABOLISM',
    'H': 'METABOLISM',
    'I': 'METABOLISM',
    'P': 'METABOLISM',
    'Q': 'METABOLISM',
    'R': 'POORLY CHARACTERIZED',
    'S': 'POORLY CHARACTERIZED'
}

# Ajout des colonnes

# 1. Extraire la première lettre du/des code(s) COG (certaines cellules peuvent contenir plusieurs codes, ex: "K,L")
dfs['COG_code'] = dfs['COG_Category'].str[0]  # Prend la première lettre (ou NaN si vide)

# 2. Mapper la fonction COG
dfs['COG_Function'] = dfs['COG_code'].map(cog_functions)

# 3. Mapper la grande catégorie
dfs['COG_Category'] = dfs['COG_code'].map(cog_categories)

columns = list(dfs.columns)
columns.insert(columns.index('COG_Category'), columns.pop(columns.index('COG_Function')))
dfs = dfs[columns]

dfs

,Sequence_ID,Seed_Ortholog,E_value,Score,eggNOG_OGs,Max_Annotation_Level,COG_Function,COG_Category,Function_Description,Annotated_Gene_Name,...,KEGG_Module,KEGG_Reaction,KEGG_rClass,KEGG_BRITE,KEGG_TC,CAZy,BiGG_Reaction,Pfam_Domains,Organisme,COG_code
0,NODE_1_length_15763_cov_36.459273_g0_i0,2880.D7FN30,2.750000e-14,90.1,"COG5245@1|root,KOG3595@2759|Eukaryota",2759|Eukaryota,Cytoskeleton,CELLULAR PROCESSES AND SIGNALING,dynein light chain binding,<NA>,...,<NA>,<NA>,<NA>,"ko00000,ko00001,ko04812",<NA>,<NA>,<NA>,"AAA_5,AAA_6,AAA_7,AAA_8,AAA_9,DHC_N2,Dynein_he...",Lingulodinium,Z
1,NODE_2_length_13913_cov_31.548410_g1_i0,99598.Cal7507_1772,2.150000e-33,152.0,"COG2931@1|root,COG3210@1|root,COG2931@2|Bacter...",1117|Cyanobacteria,"Secondary metabolites biosynthesis, transport ...",METABOLISM,Haemolysin-type calcium-binding repeat (2 copies),<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"HemolysinCabind,VCBS",Lingulodinium,Q
2,NODE_3_length_13771_cov_81.442181_g2_i0,99598.Cal7507_1772,2.190000e-42,182.0,"COG2931@1|root,COG3210@1|root,COG2931@2|Bacter...",1117|Cyanobacteria,"Secondary metabolites biosynthesis, transport ...",METABOLISM,Haemolysin-type calcium-binding repeat (2 copies),<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"HemolysinCabind,VCBS",Lingulodinium,Q
3,NODE_4_length_13567_cov_10.538758_g3_i0,34506.g5327,1.740000e-240,780.0,"COG0097@1|root,COG0098@1|root,COG0099@1|root,C...",33208|Metazoa,"Translation, ribosomal structure and biogenesis",INFORMATION STORAGE AND PROCESSING,Ribosomal protein S11,MRPS11,...,"M00178,M00179",<NA>,<NA>,"br01610,ko00000,ko00001,ko00002,ko03011",<NA>,<NA>,<NA>,Ribosomal_S11,Lingulodinium,J
4,NODE_5_length_13132_cov_25.985297_g4_i0,529818.AMSG_02133T0,0.000000e+00,1387.0,"COG5126@1|root,KOG0027@2759|Eukaryota",2759|Eukaryota,"Cell cycle control, cell division, chromosome ...",CELLULAR PROCESSES AND SIGNALING,Calcium-binding protein,EFCAB2,...,<NA>,<NA>,<NA>,"ko00000,ko00001,ko01009,ko03019,ko03021,ko0303...",<NA>,<NA>,<NA>,"EF-hand_7,EFhand_Ca_insen",Lingulodinium,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147935,rb_31299,411467.BACCAP_03832,3.600000e-25,100.0,"2DN97@1|root,32W7A@2|Bacteria,1VANB@1239|Firmi...",186801|Clostridia,NaN,NaN,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Karlodinium,<NA>
147936,rb_31336,1121024.AUCD01000033_gene1958,2.080000e-12,65.9,"2DTS4@1|root,33MFD@2|Bacteria,1VKHK@1239|Firmi...",91061|Bacilli,NaN,NaN,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Karlodinium,<NA>
147937,rb_31337,1499502.EV12_2437,6.340000e-04,45.4,"COG3258@1|root,COG3258@2|Bacteria,1G07V@1117|C...",1117|Cyanobacteria,Energy production and conversion,METABOLISM,"Component of the cytochrome b6-f complex, whic...",petA,...,M00162,<NA>,<NA>,"ko00000,ko00001,ko00002,ko00194",<NA>,<NA>,<NA>,"Apocytochr_F_C,Apocytochr_F_N",Karlodinium,C
147938,rb_31360,2754.EH55_12370,3.420000e-15,79.3,"COG0051@1|root,COG0051@2|Bacteria,3TB4W@508458...",508458|Synergistetes,"Translation, ribosomal structure and biogenesis",INFORMATION STORAGE AND PROCESSING,Involved in the binding of tRNA to the ribosomes,rpsJ,...,"M00178,M00179",<NA>,<NA>,"br01610,ko00000,ko00001,ko00002,ko03011",<NA>,<NA>,<NA>,Ribosomal_S10,Karlodinium,J
147939,rb_31364,4792.ETI45264,9.520000e-64,204.0,"COG5201@1|root,KOG1724@2759|Eukaryota,3QASU@47...",4776|Peronosporales,"Posttranslational modification, protein turnov...",CELLULAR PROCESSES AND SIGNALING,Found in Skp1 protein family,<NA>,...,"M00379,M00380,M00381,M00382,M00387,M00407,M00411",<NA>,<NA>,"ko00000,ko00001,ko00002,ko03036,ko04121",<NA>,<NA>,<NA>,"Skp1,Skp1_POZ",Karlodinium,O

In [6]:
annotes = dfs['Organisme'].value_counts()
# ✅ Calcul annotés vs non annotés
stat_finale = pd.DataFrame({
    "Total_transcrits": pd.Series(totaux_transcrits),
    "Annotés": annotes
})
stat_finale["Non_annotés"] = stat_finale["Total_transcrits"] - stat_finale["Annotés"]
stat_finale["% annotés"] = (stat_finale["Annotés"] / stat_finale["Total_transcrits"] * 100).round(2)

print(stat_finale)

               Total_transcrits  Annotés  Non_annotés  % annotés
Dinophysis               112582    31877        80705      28.31
Karlodinium              136385    50552        85833      37.07
Lingulodinium            122606    36390        86216      29.68
Prymnesium                84071    29121        54950      34.64

In [ ]:
dfs.to_csv("All_annotations.csv", index=False)